CREATE TABLE IF NOT EXISTS AlgorithmStatus (
    ID SERIAL PRIMARY KEY,
    ClientID SERIAL references clients(ID),
    VWAP BOOLEAN DEFAULT FALSE,
    TWAP BOOLEAN DEFAULT FALSE,
    HFT BOOLEAN DEFAULT FALSE
    );