CREATE TABLE AlgorithmStatus (
    ID SERIAL PRIMARY KEY,
    FOREIGN KEY (ClientID) REFERENCES Clients(ID),
    VWAP BOOLEAN DEFAULT FALSE,
    TWAP BOOLEAN DEFAULT FALSE,
    HFT BOOLEAN DEFAULT FALSE,
);