CREATE TABLE IF NOT EXISTS algorithm_status (
    ID SERIAL PRIMARY KEY,
    ClientID SERIAL references clients(ID),
    VWAP BOOLEAN DEFAULT FALSE,
    TWAP BOOLEAN DEFAULT FALSE,
    HFT BOOLEAN DEFAULT FALSE
);