CREATE TABLE IF NOT EXISTS algorithm_status (
    ID SERIAL PRIMARY KEY,
    ClientID INTEGER UNIQUE references clients(ID)  ON DELETE CASCADE,
    VWAP BOOLEAN DEFAULT FALSE,
    TWAP BOOLEAN DEFAULT FALSE,
    HFT BOOLEAN DEFAULT FALSE
);